# Generated by Django 5.2.1 on 2025-06-22 09:01
from django.utils import timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    def create_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()

        if User.objects.exists():
            return
        
        superuser = User.objects.create_superuser(
            username = "admin",
            email = "admin@admin.com",
            password= "admin123",
            last_login = timezone.now()
        )

        superuser.save()

    operations = [
        migrations.RunPython(create_superuser)
    ]
