# Generated by Django 5.2.1 on 2025-06-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_alter_article_content_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
