# Generated by Django 5.2.1 on 2025-07-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('in_progress', 'in progress'), ('published', 'published')], default='draft', max_length=20, verbose_name='status'),
        ),
    ]
